components {
  id: "mirror.collisionobject"
  component: "/game/main/mirror/mirror.collisionobject"
}
components {
  id: "mirror"
  component: "/game/main/mirror/mirror.script"
}
embedded_components {
  id: "sprite"
  type: "sprite"
  data: "default_animation: \"Mirror\"\n"
  "material: \"/builtins/materials/sprite.material\"\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/game/images/atlas.atlas\"\n"
  "}\n"
  ""
  scale {
    x: 0.495704
    y: 0.263537
  }
}
embedded_components {
  id: "mirrorMove"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_TRIGGER\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"mirrorMove\"\n"
  "mask: \"mouse\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "  }\n"
  "  data: 2.08\n"
  "  data: 5.525527\n"
  "  data: 10.0\n"
  "}\n"
  ""
}
embedded_components {
  id: "mirrorRotate"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_TRIGGER\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"mirrorRotate\"\n"
  "mask: \"mouse\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      y: 7.3\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      y: -7.24\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 3\n"
  "    count: 3\n"
  "  }\n"
  "  data: 2.08\n"
  "  data: 1.59955\n"
  "  data: 10.0\n"
  "  data: 2.08\n"
  "  data: 1.59955\n"
  "  data: 10.0\n"
  "}\n"
  ""
}
embedded_components {
  id: "mirrorBlock"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_KINEMATIC\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.0\n"
  "group: \"mirror_block\"\n"
  "mask: \"mirror_block\"\n"
  "mask: \"wall\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_SPHERE\n"
  "    position {\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 1\n"
  "  }\n"
  "  data: 9.145229\n"
  "}\n"
  ""
}
