components {
  id: "reciver"
  component: "/game/main/reciver/reciver.collisionobject"
}
components {
  id: "reciver1"
  component: "/game/main/reciver/reciver.script"
}
embedded_components {
  id: "sprite"
  type: "sprite"
  data: "default_animation: \"LaserReciver\"\n"
  "material: \"/builtins/materials/sprite.material\"\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/game/images/atlas.atlas\"\n"
  "}\n"
  ""
}
embedded_components {
  id: "collisionobject"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_KINEMATIC\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"wall\"\n"
  "mask: \"laser\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: 3.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: -7.0\n"
  "      y: 8.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 3\n"
  "    count: 3\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: -7.0\n"
  "      y: -8.6\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 6\n"
  "    count: 3\n"
  "  }\n"
  "  data: 10.005649\n"
  "  data: 12.965114\n"
  "  data: 10.0\n"
  "  data: 5.986851\n"
  "  data: 4.8865514\n"
  "  data: 10.0\n"
  "  data: 5.986851\n"
  "  data: 4.463563\n"
  "  data: 10.0\n"
  "}\n"
  ""
}
