components {
  id: "mirror"
  component: "/main/mirror/mirror.script"
}
embedded_components {
  id: "sprite"
  type: "sprite"
  data: "default_animation: \"splitmirror\"\n"
  "material: \"/builtins/materials/sprite.material\"\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/images/atlas.atlas\"\n"
  "}\n"
  ""
  position {
    x: -1.0
  }
  rotation {
    z: 0.38268343
    w: 0.9238795
  }
  scale {
    x: 0.41
    y: 0.41
  }
}
embedded_components {
  id: "mirrorMove"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_KINEMATIC\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"mirrorMove\"\n"
  "mask: \"mouse\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "    }\n"
  "    rotation {\n"
  "      x: 0.009253348\n"
  "      y: 0.00380345\n"
  "      z: -0.3801536\n"
  "      w: 0.92486924\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "  }\n"
  "  data: 3.7887034\n"
  "  data: 3.7852094\n"
  "  data: 10.0\n"
  "}\n"
  ""
}
embedded_components {
  id: "mirrorRotate"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_KINEMATIC\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"mirrorRotate\"\n"
  "mask: \"mouse\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: 3.0\n"
  "      y: -4.0\n"
  "    }\n"
  "    rotation {\n"
  "      z: 0.38268343\n"
  "      w: 0.9238795\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: 3.0\n"
  "      y: 4.0\n"
  "    }\n"
  "    rotation {\n"
  "      z: 0.38268343\n"
  "      w: 0.9238795\n"
  "    }\n"
  "    index: 3\n"
  "    count: 3\n"
  "  }\n"
  "  data: 4.4856825\n"
  "  data: 1.13858\n"
  "  data: 10.0\n"
  "  data: 1.2308955\n"
  "  data: 4.4713507\n"
  "  data: 10.0\n"
  "}\n"
  ""
}
embedded_components {
  id: "collisionobject"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_KINEMATIC\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"mirror\"\n"
  "mask: \"laser\"\n"
  "mask: \"cursor\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: -1.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "    id: \"splitmirrorreflect\"\n"
  "  }\n"
  "  data: 0.8234945\n"
  "  data: 7.321797\n"
  "  data: 10.0\n"
  "}\n"
  ""
}
embedded_components {
  id: "collisionobject1"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_KINEMATIC\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"wall\"\n"
  "mask: \"laser\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: -1.5\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "  }\n"
  "  data: 0.274037\n"
  "  data: 7.512724\n"
  "  data: 10.0\n"
  "}\n"
  ""
}
